version: '3.8'

services:
  bia-app:
    build:
      context: .
      dockerfile: Dockerfile.new
    ports:
      - "3002:8080"
    environment:
      - PORT=8080
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/versao"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
